version: '3'
services:
    dockerangular-service:
      build: .
      volumes:
        - .:/usr/app
        - /usr/app/node_modules
      environment:
        NODE_ENV: development
      ports:
        - 4200:4200
      command: "npm run start"
